export const humanOSIndicators = [
  {
    title: "Wellbeing Score",
    titleZh: "Wellbeing Score",
    basis: "WHO-5 / WEMWBS style",
    basisZh: "參考 WHO-5 / WEMWBS 方向",
    output: "Overall wellbeing awareness, vitality, calmness, and daily purpose.",
    outputZh: "整體福祉 awareness、活力、平靜感同日常意義感。",
  },
  {
    title: "Stress Index",
    titleZh: "Stress Index",
    basis: "PSS-10 style",
    basisZh: "參考 PSS-10 感知壓力方向",
    output: "Perceived overload, control pressure, unpredictability, and recovery gap.",
    outputZh: "感知負荷、控制感壓力、不可預測感同恢復缺口。",
  },
  {
    title: "Burnout Awareness",
    titleZh: "倦怠 Awareness",
    basis: "MBI / OLBI style, custom non-proprietary items",
    basisZh: "參考 MBI / OLBI 方向，但用自家非 proprietary 題目",
    output: "Exhaustion, disengagement, and progress confidence signals.",
    outputZh: "耗竭、疏離感同進展信心訊號。",
  },
  {
    title: "Sleep Recovery",
    titleZh: "睡眠恢復",
    basis: "Daily check-in + sleep quality structure",
    basisZh: "自家 daily check-in + 睡眠質素結構",
    output: "Sleep duration, quality, consistency, and daytime energy impact.",
    outputZh: "睡眠時長、質素、規律同日間能量影響。",
  },
  {
    title: "Focus & Motivation",
    titleZh: "專注及動力",
    basis: "Student / employee daily state questions",
    basisZh: "學生 / 員工日常狀態題",
    output: "Focus readiness, motivation, energy, and cognitive load.",
    outputZh: "專注準備度、動力、能量同認知負荷。",
  },
  {
    title: "Work / Study Environment",
    titleZh: "工作 / 學習環境",
    basis: "COPSOQ / HSE / UWES / psychological safety style",
    basisZh: "參考 COPSOQ / HSE / UWES / 心理安全感方向",
    output: "Workload, support, role clarity, belonging, engagement, and team safety.",
    outputZh: "工作量、支援、角色清晰、歸屬感、投入度同團隊安全感。",
  },
] as const;

export const assessmentLibrary = [
  {
    name: "Daily Pulse Check",
    nameZh: "每日 Pulse Check",
    cadence: "Daily · 6 items",
    cadenceZh: "每日 · 6 題",
    inspiredBy: "HumanOS custom pulse model",
    inspiredByZh: "HumanOS 自家 pulse model",
    purpose: "A fast daily snapshot across stress, sleep, focus, workload, mood, and support needs.",
    purposeZh: "每日快速了解壓力、睡眠、專注、工作量 / 學業量、心情同支援需要。",
    outputs: ["Wellbeing awareness", "Stress trend", "Support suggestion"],
    outputsZh: ["福祉 awareness", "壓力趨勢", "支援建議"],
    visibility: "Personal result only; institution sees anonymous trend.",
    visibilityZh: "個人結果只俾用戶睇；機構只睇匿名趨勢。",
  },
  {
    name: "Weekly Wellbeing Check",
    nameZh: "每週 Wellbeing Check",
    cadence: "Weekly · WHO-5 / WEMWBS style",
    cadenceZh: "每週 · WHO-5 / WEMWBS 方向",
    inspiredBy: "Positive wellbeing, vitality, calmness, interest, and purpose frameworks",
    inspiredByZh: "參考 positive wellbeing、活力、平靜、興趣同意義感框架",
    purpose: "Build the HumanOS Wellbeing Score without presenting a clinical label.",
    purposeZh: "建立 HumanOS Wellbeing Score，但唔展示臨床標籤。",
    outputs: ["Wellbeing Score", "Positive wellbeing trend", "Recovery suggestion"],
    outputsZh: ["Wellbeing Score", "Positive wellbeing 趨勢", "恢復建議"],
    visibility: "Individuals see their own profile; schools and HR see aggregated wellbeing movement.",
    visibilityZh: "個人睇自己 profile；學校同 HR 只睇整體 wellbeing movement。",
  },
  {
    name: "Monthly Burnout Check",
    nameZh: "每月倦怠 Check",
    cadence: "Monthly · OLBI / MBI style",
    cadenceZh: "每月 · OLBI / MBI 方向",
    inspiredBy: "Exhaustion, disengagement, cynicism, and efficacy research",
    inspiredByZh: "參考耗竭、疏離 / 冷感、效能感研究",
    purpose: "Surface burnout risk awareness using custom non-proprietary items.",
    purposeZh: "用自家非 proprietary 題目呈現倦怠風險 awareness。",
    outputs: ["Burnout risk awareness", "Recovery gap", "Referral suggestion when needed"],
    outputsZh: ["倦怠風險 awareness", "恢復缺口", "需要時建議轉介"],
    visibility: "No individual burnout result is shown to institutions.",
    visibilityZh: "個人倦怠結果唔會俾機構睇。",
  },
  {
    name: "Workplace Module",
    nameZh: "職場 Module",
    cadence: "Monthly / campaign-based",
    cadenceZh: "每月 / 按 campaign",
    inspiredBy: "COPSOQ, HSE Management Standards, UWES, psychological safety style",
    inspiredByZh: "參考 COPSOQ、HSE Management Standards、UWES、心理安全感方向",
    purpose: "Help HR understand workload, support, role clarity, engagement, and team safety anonymously.",
    purposeZh: "幫 HR 匿名了解工作量、支援、角色清晰、投入度同團隊安全感。",
    outputs: ["Workforce intelligence", "Campaign ROI", "Department trend"],
    outputsZh: ["Workforce intelligence", "Campaign ROI", "部門趨勢"],
    visibility: "Only anonymized department, shift, or cohort trends.",
    visibilityZh: "只顯示匿名部門、輪班或群組趨勢。",
  },
  {
    name: "Student Module",
    nameZh: "學生 Module",
    cadence: "Weekly / exam-period pulse",
    cadenceZh: "每週 / 考試期 pulse",
    inspiredBy: "Academic stress, belonging, support, sleep, focus, and motivation frameworks",
    inspiredByZh: "參考學業壓力、歸屬感、支援、睡眠、專注同動力框架",
    purpose: "Help students understand their own state and help schools identify anonymous support needs early.",
    purposeZh: "幫學生理解自己狀態，亦幫學校及早發現匿名支援需要。",
    outputs: ["Study pressure trend", "Sleep and focus support", "Belonging and support signal"],
    outputsZh: ["學習壓力趨勢", "睡眠及專注支援", "歸屬感及支援訊號"],
    visibility: "Schools never see private reflections or individual AI conversations.",
    visibilityZh: "學校永遠唔睇私人反思或個人 AI 對話。",
  },
] as const;

export const recognizedQuestionnaires = [
  {
    name: "WHO-5 Well-Being Index",
    audience: "Personal / student / employee",
    use: "Overall mental wellbeing; suitable as a reference for the HumanOS Wellbeing Score.",
    useZh: "整體心理福祉；適合作為 HumanOS Wellbeing Score 參考底層。",
    humanOSUse: "Weekly Wellbeing Check",
  },
  {
    name: "WEMWBS / SWEMWBS",
    audience: "Student / general population",
    use: "Positive mental wellbeing; suitable for a student positive wellbeing module.",
    useZh: "Positive mental wellbeing；適合學生版 positive wellbeing module。",
    humanOSUse: "Weekly Wellbeing Check",
  },
  {
    name: "PSS-10 Perceived Stress Scale",
    audience: "Personal / student / employee",
    use: "Perceived uncontrollability, unpredictability, and overload; suitable for Stress Index.",
    useZh: "感知不可控、不可預測及負荷過重；適合 Stress Index。",
    humanOSUse: "Stress Index",
  },
  {
    name: "PHQ-9",
    audience: "Personal depth self-check only",
    use: "Depression screening reference; not suitable as a homepage or institutional dashboard metric.",
    useZh: "Depression screening 參考；不建議放首頁或機構 dashboard。",
    humanOSUse: "Private referral awareness only",
  },
  {
    name: "GAD-7",
    audience: "Personal depth self-check only",
    use: "Anxiety screening reference; should stay private and referral-oriented.",
    useZh: "Anxiety screening 參考；應保持私密，只作轉介 awareness。",
    humanOSUse: "Private referral awareness only",
  },
  {
    name: "Maslach Burnout Inventory",
    audience: "Employee / HR",
    use: "Burnout dimensions such as emotional exhaustion, cynicism, and professional efficacy; many uses require licensing.",
    useZh: "倦怠維度如 emotional exhaustion、cynicism、professional efficacy；多數使用需授權。",
    humanOSUse: "Burnout Awareness reference only",
  },
  {
    name: "Oldenburg Burnout Inventory",
    audience: "Employee / HR",
    use: "Exhaustion and disengagement; useful for a burnout awareness model.",
    useZh: "量度 exhaustion 同 disengagement；適合做 burnout awareness 參考。",
    humanOSUse: "Monthly Burnout Check",
  },
  {
    name: "COPSOQ III",
    audience: "Workplace / HR",
    use: "Psychosocial workplace risks across demands, organization, leadership, and relations.",
    useZh: "工作場所心理社會風險，包括需求、組織、領導及關係。",
    humanOSUse: "Workplace Module",
  },
  {
    name: "HSE Management Standards Indicator Tool",
    audience: "Workplace / HR",
    use: "Work stress sources such as demands, control, support, relationships, role, and change.",
    useZh: "工作壓力來源，包括 demands、control、support、relationships、role、change。",
    humanOSUse: "Workplace Module",
  },
  {
    name: "UWES Utrecht Work Engagement Scale",
    audience: "Employee / HR",
    use: "Work engagement across vigor, dedication, and absorption.",
    useZh: "量度 work engagement，包括 vigor、dedication、absorption。",
    humanOSUse: "Engagement / motivation signal",
  },
  {
    name: "Edmondson Psychological Safety Scale",
    audience: "Team / HR",
    use: "Team safety for speaking up, asking questions, and admitting mistakes.",
    useZh: "團隊能否安全提出問題、承認錯誤、表達不同意見。",
    humanOSUse: "Team Safety signal",
  },
] as const;

export const assessmentSafetyPrinciples = [
  "Do not show diagnosis results.",
  "Show wellbeing awareness, stress trend, burnout risk awareness, support suggestions, and referral suggestions when needed.",
  "Keep PHQ-9 / GAD-7 style content private and referral-oriented only.",
  "Use custom items inspired by frameworks; do not copy proprietary questionnaire wording.",
  "Institutions see anonymized trends, not individual answers, journals, reports, or AI conversations.",
] as const;
